{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9f96a2f7-62fe-4614-a5b5-89c0f74ba427",
   "metadata": {},
   "outputs": [],
   "source": [
    "import datetime\n",
    "import time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "b9162c35-5926-45ef-adbc-753a46f790fb",
   "metadata": {},
   "outputs": [],
   "source": [
    "class renting_Cars():\n",
    "    \n",
    "    def __init__(self,cars_available):\n",
    "        self.cars_available = cars_available\n",
    "        pass;\n",
    "    def available_Cars(self,cars_needed):\n",
    "        # self.cars_available = 20;\n",
    "        if self.cars_available < cars_needed:\n",
    "            print(f' Only {self.cars_available} are available')\n",
    "            return False;\n",
    "        else :\n",
    "            print(f\" Congrats {cars_needed} cars are available\");\n",
    "            self.cars_available -=  cars_needed;\n",
    "            print(cars_available)\n",
    "            return True;\n",
    "            \n",
    "    def weekly(self):\n",
    "         duration = int(input('Enter Week duration from now:'))\n",
    "         start_time = datetime.now()\n",
    "         str_time = start_time.strftime(\"%b %d %Y %I:%M%p\")\n",
    "         print(f\"Kindly note your start time : \\n {str_time}\")\n",
    "         return start_time;\n",
    "         \n",
    "    def hourly(self):\n",
    "        duration = int(input('Enter Hour duration from now:'))\n",
    "        start_time = datetime.now()\n",
    "        str_time = start_time.strftime(\"%b %d %Y %I:%M%p\")\n",
    "        print(f\"Kindly note your start time : \\n {str_time}\")\n",
    "        return start_time;\n",
    "        \n",
    "        \n",
    "    def daily(self):\n",
    "         duration = int(input('Enter Day duration from now:'))\n",
    "         start_time = datetime.datetime.now()\n",
    "         str_time = start_time.strftime(\"%b %d %Y %I:%M%p\")\n",
    "         print(f\"Kindly note your start time : \\n {str_time}\")\n",
    "         return start_time;\n",
    "\n",
    "    def car_Return(self,rental_type,rented_Cars):\n",
    "            \n",
    "            start_date=input(\"Enter the start Date and Time of your rental \\n (Ex-Jan 1 2000 12:00AM)\")\n",
    "            format = '%b %d %Y %I:%M%p'\n",
    "            rental_start_time = datetime.datetime.strptime(start_date, format)\n",
    "            self.cars_available += rented_Cars \n",
    "            if rental_start_time > datetime.datetime.now():\n",
    "                print(\"Enter Valid Date\")\n",
    "            else:\n",
    "                current_time = datetime.datetime.now()\n",
    "                Total_rental_time = current_time - rental_start_time\n",
    "                # inbulit function used to convert day and hrs into hrs format\n",
    "                deltatime=datetime.timedelta(days=Total_rental_time.days,seconds=Total_rental_time.seconds)\n",
    "                hours=float(deltatime.days * 24 + deltatime.seconds // 3600)\n",
    "              \n",
    "                rented_Cars = int(input(\"No of Cars Rented: \"))\n",
    "            if rental_type == 1:\n",
    "                # HOURLY RENTAL CHARGES\n",
    "                 \n",
    "                 Rent = 100 * hours *  rented_Cars\n",
    "                 print(f\" Your Total Rental Hours: {hours} \\n Bill Amount : {Rent}\")\n",
    "            elif rental_type == 2:\n",
    "                # DAILY RENTAL CHARGES\n",
    "                 Rent = 90 * hours *  rented_Cars\n",
    "                 print(f\" Your Total Rental Hours: {hours} \\n Bill Amount : {Rent}\") \n",
    "            elif rental_type == 3:\n",
    "                # WEEKLY RENTAL CHARGES\n",
    "                 Rent = 85 * hours *  rented_Cars\n",
    "                 print(f\" Your Total Rental Hours: {hours} \\n Bill Amount : {Rent}\")\n",
    "            return Rent;\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "4caf2daa-a77d-4249-b54d-ac3699dd6c56",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "class customer(renting_Cars):\n",
    "    def __init__(self):\n",
    "        pass\n",
    "        \n",
    "    def request_Cars(cars):\n",
    "       cars_Available = renting_Car.available_Cars(cars_needed)\n",
    "       if cars_Available == True:\n",
    "           print(\"Select Your Rental Type\" )\n",
    "           print(\" 1 - Hourly \\n 2 - Day \\n 3 - Week\")\n",
    "           rental_type = int(input())\n",
    "           if rental_type == 1:\n",
    "               Time = Obj1.hourly()\n",
    "           elif rental_type == 2:\n",
    "                Time = Obj1.daily()\n",
    "           elif rental_type == 3:\n",
    "                Time = Obj1.weekly()\n",
    "           else :\n",
    "                print(\"Enter Valid number\") \n",
    "       return Time;\n",
    "                \n",
    "        \n",
    "    def return_Cars():\n",
    "        print(\"Select Your Rental Type\" )\n",
    "        print(\" 1 - Hourly \\n 2 - Day \\n 3 - Week\")\n",
    "        rental_type = int(input())\n",
    "        if rental_type < 3 & rental_type > 0 :\n",
    "            Rental_Amount = renting_Cars.car_Return(rental_type)\n",
    "        else :\n",
    "            print(\"Enter a Valid Number : \")\n",
    "        return Rental_Amount;\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   # "execution_count": 0,
   "id": "8c2faffd-2005-4a24-b63e-0f255894dcde",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "id": "e9e07313-c07f-4716-b395-212c083083ca",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "id": "45dae30b-0731-4886-975f-719cb4fa4e5e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
